//! Documentation text transformations.
//!
//! Converts `$ `‐prefixed `console` code blocks into calls to Zola's `terminal`
//! component, and fences off the template syntax Worktrunk *documents* so Zola
//! doesn't try to evaluate it. Used by both the `--help-page` generator (CLI
//! source → web docs) and the doc sync test (hand-written docs → web docs).
//!
//! Zola 0.23 (Tera2) removed shortcodes in favour of components and started
//! rendering every `.md` file through the template engine, which is what makes
//! the second transformation necessary: a documented minijinja example such as
//! `{{ branch | hash_port }}` is otherwise read as a Zola expression and fails
//! the build. [`wrap_template_syntax`] wraps those in `{% raw %}`, and
//! [`strip_template_syntax_wrappers`] is its exact inverse — the doc sync test
//! strips on read and wraps on write so a page compares against its source
//! form, not its published one.

/// Empty span; the displayed "EXPERIMENTAL" text comes from the CSS `::after`
/// rule so the anchor-link slug generated by Zola ignores it.
///
/// Lives here (rather than in `src/help.rs`) so the producer (the `--help-page`
/// post-processor that emits this in place of `[experimental]`) and the
/// consumer (the skill-file generator that strips it back to `[experimental]`)
/// stay in lockstep — changing the badge in one place would otherwise let
/// stale HTML leak silently into skill files.
pub const BADGE_EXPERIMENTAL_HTML: &str = "<span class=\"badge-experimental\"></span>";

/// HTML-comment marker that includes a subcommand's `--help-page` body inline
/// in its parent's `after_long_help`. Expanded into an H2 section by
/// `expand_subdoc_placeholders`. Trailing space included so `find()` and
/// `strip_prefix()` agree on the boundary.
pub const SUBDOC_MARKER_PREFIX: &str = "<!-- subdoc: ";

/// HTML-comment marker that pulls a demo GIF from `worktrunk-assets` into the
/// docs site (rendered as a `<picture>` figure). Stripped from skill output.
pub const DEMO_MARKER_PREFIX: &str = "<!-- demo: ";

/// Open-marker prefix for an auto-generated region in a docs file.
/// Followed by `<id> — edit <source> to update -->`. Both `--help-page` (the
/// producer in `src/help.rs`) and the doc-sync test (the consumer in
/// `tests/integration_tests/readme_sync.rs`) reference this so the literal
/// can't drift between sides.
pub const MARKER_OPEN_PREFIX: &str = "<!-- ⚠️ AUTO-GENERATED from ";

/// Close marker for an auto-generated region. Paired with `MARKER_OPEN_PREFIX`
/// via non-greedy regex matching; the sync test
/// `test_no_nested_auto_generated_markers` enforces the no-nesting precondition
/// that makes that pairing safe.
pub const MARKER_CLOSE: &str = "<!-- END AUTO-GENERATED -->";

/// Convert `$ `‐prefixed console blocks into `terminal` component calls.
///
/// All shell commands in `console` blocks use `$ ` prefix. This function detects
/// them and emits the appropriate call form:
///
/// - Commands without output: `{{ <terminal cmd="..." /> }}` (Syntect highlighting)
/// - Commands with output: `{% <terminal cmd="..."> %}output{% </terminal> %}`
/// - Multiple commands/comments: `|||`‐delimited in `cmd` parameter
///
/// `{{ }}` in commands (e.g., Jinja2 template expressions) are replaced with
/// placeholders so Tera doesn't interpret them. The `terminal` component
/// replaces them back before Syntect highlighting. Double quotes and backslashes
/// get the same treatment: the first would close the `cmd="..."` argument, and
/// the second is Tera2's string-escape character, so a shell continuation `\`
/// left as-is is either an "unexpected escape character" build error or —
/// worse, for a sequence Tera2 does recognise — a silent rewrite.
///
/// Blocks without `$ ` are left unchanged for the `console` → `bash` replacement.
pub fn convert_dollar_console_to_terminal(text: &str) -> String {
    let mut result = String::with_capacity(text.len());
    let mut lines = text.lines().peekable();

    while let Some(line) = lines.next() {
        if line.trim_start() == "```console" {
            // Collect the block, then decide whether to convert
            let mut block_lines = Vec::new();
            for content_line in lines.by_ref() {
                let stripped = content_line.trim_start();
                if stripped.starts_with("```")
                    && (stripped.len() == 3 || !stripped.as_bytes()[3].is_ascii_alphabetic())
                {
                    break;
                }
                block_lines.push(content_line);
            }

            // Only convert if the block contains $ commands
            let commands: Vec<_> = block_lines
                .iter()
                .filter_map(|l| l.strip_prefix("$ "))
                .collect();

            if commands.is_empty() {
                // No $ lines — emit unchanged as console block
                result.push_str(line);
                result.push('\n');
                for bl in &block_lines {
                    result.push_str(bl);
                    result.push('\n');
                }
                result.push_str("```\n");
                continue;
            }

            // Classify each line into the cmd= stream (rendered with prompt
            // prefix and Syntect highlighting, joined by `|||`) or the output
            // body. `$ <cmd>` lines feed cmd= verbatim (with `"` and `{{`/`}}`
            // escaped past Tera); `#` lines feed cmd= so the template styles
            // them as bash-comment section headers (used by the `wt list` jq
            // recipes block). Blank lines belong to whichever side has content
            // — to cmd= when the block is command-only (visual spacing between
            // recipe groups), to body otherwise.
            let has_output = block_lines
                .iter()
                .any(|l| !l.is_empty() && !l.starts_with("$ ") && !l.starts_with('#'));
            let mut cmd_value: Vec<String> = Vec::new();
            let mut body_lines: Vec<&&str> = Vec::new();
            for line in &block_lines {
                if let Some(cmd) = line.strip_prefix("$ ") {
                    cmd_value.push(
                        cmd.replace('\\', "__WT_BSLASH__")
                            .replace('"', "__WT_QUOT__")
                            .replace("{{", "__WT_OPEN__")
                            .replace("}}", "__WT_CLOSE__"),
                    );
                } else if line.starts_with('#') || (line.is_empty() && !has_output) {
                    cmd_value.push((*line).to_string());
                } else {
                    body_lines.push(line);
                }
            }

            let cmd_str = cmd_value.join("|||");
            if body_lines.is_empty() {
                result.push_str(&format!("{{{{ <terminal cmd=\"{cmd_str}\" /> }}}}\n"));
            } else {
                result.push_str(&format!("{{% <terminal cmd=\"{cmd_str}\"> %}}\n"));
                for bl in &body_lines {
                    result.push_str(bl);
                    result.push('\n');
                }
                result.push_str("{% </terminal> %}\n");
            }
            continue;
        }
        result.push_str(line);
        result.push('\n');
    }

    // .lines() strips the trailing newline; match original
    if !text.ends_with('\n') {
        result.pop();
    }
    result
}

/// The two sequences a `{% raw %}` region cannot carry literally: its own
/// delimiters. Emitted in their place, each closes the region, prints the
/// literal through a string expression, and reopens. Both halves of the
/// wrap/strip pair key on this exact text, which is what lets strip tell an
/// emitted delimiter from a documented one and stay an exact inverse.
const ENDRAW_ESCAPE: &str = r#"{% endraw %}{{ "{% endraw %}" }}{% raw %}"#;
const RAW_ESCAPE: &str = r#"{% endraw %}{{ "{% raw %}" }}{% raw %}"#;

const RAW_OPEN: &str = "{% raw %}";
const RAW_CLOSE: &str = "{% endraw %}";

/// Replace both raw delimiters with their escapes in one pass, so the
/// `{% raw %}` each escape ends with isn't itself escaped.
fn escape_raw_delimiters(line: &str) -> String {
    line.split(RAW_CLOSE)
        .map(|between| between.replace(RAW_OPEN, RAW_ESCAPE))
        .collect::<Vec<_>>()
        .join(ENDRAW_ESCAPE)
}

/// Mirror image of [`escape_raw_delimiters`], in the same one pass, so a
/// restored delimiter can't be read as part of the other escape.
fn unescape_raw_delimiters(line: &str) -> String {
    line.split(ENDRAW_ESCAPE)
        .map(|between| between.replace(RAW_ESCAPE, RAW_OPEN))
        .collect::<Vec<_>>()
        .join(RAW_CLOSE)
}

/// True for a line that calls a Zola component (`{{ <terminal … /> }}`,
/// `{% <terminal …> %}`, `{% </terminal> %}`) and so must stay evaluable.
fn is_component_call(line: &str) -> bool {
    let t = line.trim_start();
    t.starts_with("{{ <") || t.starts_with("{% <")
}

fn has_template_syntax(text: &str) -> bool {
    text.contains("{{") || text.contains("{%")
}

/// Fence marker (``` or ~~~, three or more), if this line opens or closes a
/// fenced code block.
fn fence_marker(line: &str) -> Option<&str> {
    let rest = line.trim_start();
    for ch in ['`', '~'] {
        let run = rest.chars().take_while(|c| *c == ch).count();
        if run >= 3 {
            return Some(&rest[..run]);
        }
    }
    None
}

/// Fence off the template syntax the docs *document* so Zola renders it
/// literally instead of evaluating it.
///
/// Zola 0.23 templates every `.md` file, so a documented `{{ branch }}` is a
/// build error rather than text. Component calls are the only lines that have
/// to stay evaluable — they are the reason content templating is on at all —
/// so they bound the regions, and everything between two of them that carries
/// template syntax goes into *one* `{% raw %}` region rather than one per line
/// or per fenced block. A page ends up with a handful of markers instead of
/// dozens: prose that happens to sit between two documented examples is
/// covered by the same region, which costs nothing, since a raw region passes
/// its text through untouched.
///
/// The markers ride on the first and last line of the region rather than
/// sitting on lines of their own, so a region inside a paragraph or a list
/// can't introduce a blank line that would split it. Both delimiters are then
/// only ever emitted at a line's very edge, and a documented one inside a
/// region travels as an escape sequence — which is what lets
/// [`strip_template_syntax_wrappers`] undo this exactly.
///
/// Takes a page in *source* form. A published page has to be stripped first
/// (`read_docs_page` in the doc sync test does this); wrapping one twice
/// escapes the first pass's markers as documented text rather than reusing
/// them.
pub fn wrap_template_syntax(text: &str) -> String {
    let ends_with_newline = text.ends_with('\n');
    let lines: Vec<&str> = text.lines().collect();

    // Front matter is TOML read before templating; leave it alone.
    let start = if lines.first() == Some(&"+++") {
        lines
            .iter()
            .skip(1)
            .position(|l| *l == "+++")
            .map_or(0, |i| i + 2)
    } else {
        0
    };

    // A fenced block can *document* a component call, so only a call at the
    // top level bounds a region. The block's own span is recorded so a region
    // that reaches into one grows to cover it whole, keeping the markers on the
    // fence lines rather than inside the code.
    let mut bounds = vec![false; lines.len()];
    let mut block = vec![None; lines.len()];
    let mut i = 0;
    while i < lines.len() {
        if let Some(marker) = fence_marker(lines[i]) {
            let open = i;
            i += 1;
            while i < lines.len() && lines[i].trim() != marker {
                i += 1;
            }
            let close = i.min(lines.len() - 1);
            block[open..=close].fill(Some((open, close)));
            i = close + 1;
        } else {
            bounds[i] = is_component_call(lines[i]);
            i += 1;
        }
    }

    let mut out: Vec<String> = lines[..start].iter().map(|l| (*l).to_string()).collect();
    let mut i = start;
    while i < lines.len() {
        if bounds[i] {
            out.push(lines[i].to_string());
            i += 1;
            continue;
        }
        let segment_start = i;
        while i < lines.len() && !bounds[i] {
            i += 1;
        }
        let segment = segment_start..i;
        let Some(first) = segment.clone().find(|&n| has_template_syntax(lines[n])) else {
            out.extend(lines[segment].iter().map(|l| (*l).to_string()));
            continue;
        };
        let last = segment
            .clone()
            .rfind(|&n| has_template_syntax(lines[n]))
            .unwrap_or(first);
        let first = block[first].map_or(first, |(open, _)| open);
        let last = block[last].map_or(last, |(_, close)| close);
        out.extend(lines[segment_start..first].iter().map(|l| (*l).to_string()));
        let mut region: Vec<String> = lines[first..=last]
            .iter()
            .map(|l| escape_raw_delimiters(l))
            .collect();
        region[0].insert_str(0, RAW_OPEN);
        let end = region.len() - 1;
        region[end].push_str(RAW_CLOSE);
        out.extend(region);
        out.extend(
            lines[last + 1..segment.end]
                .iter()
                .map(|l| (*l).to_string()),
        );
    }

    let mut result = out.join("\n");
    if ends_with_newline {
        result.push('\n');
    }
    result
}

/// Exact inverse of [`wrap_template_syntax`] — recover the source form of a
/// page.
///
/// A region's markers only ever appear at the very start and the very end of a
/// line, and a documented `{% raw %}` / `{% endraw %}` inside a region is
/// carried by an escape sequence rather than literally — so this inverts what
/// [`wrap_template_syntax`] emits, not arbitrary text. Text that has not been
/// through wrap can still open or close a line with a bare marker (a fenced
/// `jinja` block documenting minijinja's own `raw`); those lines are blanked,
/// and the re-wrapped result is a fixed point, so the sync test won't flag the
/// loss. Document those tags mid-line, as `extending.md` and `faq.md` do.
pub fn strip_template_syntax_wrappers(text: &str) -> String {
    let ends_with_newline = text.ends_with('\n');
    let mut out: Vec<String> = Vec::new();
    for line in text.lines() {
        let line = line.strip_prefix(RAW_OPEN).unwrap_or(line);
        let line = line.strip_suffix(RAW_CLOSE).unwrap_or(line);
        out.push(unescape_raw_delimiters(line));
    }
    let mut result = out.join("\n");
    if ends_with_newline {
        result.push('\n');
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;
    use insta::assert_snapshot;

    #[test]
    fn test_wrap_template_syntax_round_trips() {
        let source = r#"+++
title = "config"
+++

Set `{{ branch }}` in the template:

```toml
worktree-path = "{{ repo_path }}/{{ branch }}"
```

{{ <terminal cmd="wt switch feat" /> }}

Plain prose stays untouched.
"#;
        let wrapped = wrap_template_syntax(source);
        // One region spans from the first documented example to the last,
        // absorbing the prose between them; the component call bounds it.
        assert_snapshot!(wrapped, @r#"
        +++
        title = "config"
        +++

        {% raw %}Set `{{ branch }}` in the template:

        ```toml
        worktree-path = "{{ repo_path }}/{{ branch }}"
        ```{% endraw %}

        {{ <terminal cmd="wt switch feat" /> }}

        Plain prose stays untouched.
        "#);
        assert_eq!(strip_template_syntax_wrappers(&wrapped), source);
    }

    #[test]
    fn test_wrap_template_syntax_escapes_documented_delimiters() {
        // extending.md documents minijinja's own `raw`, so both literal
        // delimiters have to survive a region they would otherwise end or
        // confuse strip with — including at the region's own edges.
        let source =
            "{% raw %} wraps it:\nWrap it as `{% raw %}{{ branch }}{% endraw %}` to defer.\n";
        let wrapped = wrap_template_syntax(source);
        assert_snapshot!(wrapped, @r#"
        {% raw %}{% endraw %}{{ "{% raw %}" }}{% raw %} wraps it:
        Wrap it as `{% endraw %}{{ "{% raw %}" }}{% raw %}{{ branch }}{% endraw %}{{ "{% endraw %}" }}{% raw %}` to defer.{% endraw %}
        "#);
        assert_eq!(strip_template_syntax_wrappers(&wrapped), source);
    }

    #[test]
    fn test_wrap_template_syntax_keeps_documented_component_calls_literal() {
        // A fenced block that *shows* a component call is documentation, not a
        // call — it stays inside the region rather than bounding it.
        let source = "```jinja\n{{ <terminal cmd=\"wt list\" /> }}\n```\n\n`{{ branch }}` after.\n";
        let wrapped = wrap_template_syntax(source);
        assert_snapshot!(wrapped, @r#"
        {% raw %}```jinja
        {{ <terminal cmd="wt list" /> }}
        ```

        `{{ branch }}` after.{% endraw %}
        "#);
        assert_eq!(strip_template_syntax_wrappers(&wrapped), source);
    }

    #[test]
    fn test_convert_dollar_console_to_terminal() {
        // Command+output with {{ }} → cmd parameter with placeholders
        assert_snapshot!(convert_dollar_console_to_terminal(
            "```console\n$ wt step eval '{{ branch | hash_port }}'\n16066\n```"
        ), @r#"
        {% <terminal cmd="wt step eval '__WT_OPEN__ branch | hash_port __WT_CLOSE__'"> %}
        16066
        {% </terminal> %}
        "#);

        // Command only (no $) → unchanged
        assert_snapshot!(convert_dollar_console_to_terminal(
            "```console\nwt step commit --stage=tracked\n```"
        ), @r"
        ```console
        wt step commit --stage=tracked
        ```
        ");

        // Multi-line output, no {{ }} → cmd parameter
        assert_snapshot!(convert_dollar_console_to_terminal(
            "```console\n$ wt step eval -v 'test'\n○ Available template variables\n  branch = feature/auth\ntest\n```"
        ), @r#"
        {% <terminal cmd="wt step eval -v 'test'"> %}
        ○ Available template variables
          branch = feature/auth
        test
        {% </terminal> %}
        "#);

        // Single command with output, no {{ }} → cmd parameter
        assert_snapshot!(convert_dollar_console_to_terminal(
            "```console\n$ echo 'PORT=8080' > .env\noutput\n```"
        ), @r#"
        {% <terminal cmd="echo 'PORT=8080' > .env"> %}
        output
        {% </terminal> %}
        "#);

        // Command only (single, no output) → self-closing call
        assert_snapshot!(convert_dollar_console_to_terminal(
            "```console\n$ wt remove\n```"
        ), @r#"{{ <terminal cmd="wt remove" /> }}
        "#);

        // Multiple commands → |||‐delimited cmd with Syntect highlighting
        assert_snapshot!(convert_dollar_console_to_terminal(
            "```console\n$ wt step push\n$ wt step push develop\n```"
        ), @r#"{{ <terminal cmd="wt step push|||wt step push develop" /> }}
        "#);

        // Comment before $ commands → included in cmd, Syntect highlights as comment
        assert_snapshot!(convert_dollar_console_to_terminal(
            "```console\n# Recent commands\n$ tail -5 log.jsonl | jq .\n\n# Failed\n$ jq 'select(.exit != 0)' log.jsonl\n```"
        ), @r##"{{ <terminal cmd="# Recent commands|||tail -5 log.jsonl | jq .||||||# Failed|||jq 'select(.exit != 0)' log.jsonl" /> }}
        "##);

        // Blank line in mixed-mode block (cmd + output) stays in body, doesn't
        // leak into cmd= as a stray `$ ` prompt.
        assert_snapshot!(convert_dollar_console_to_terminal(
            "```console\n$ wt list\n  Branch  Status\n@ main\n\n○ Showing 1 worktree\n```"
        ), @r#"
        {% <terminal cmd="wt list"> %}
          Branch  Status
        @ main

        ○ Showing 1 worktree
        {% </terminal> %}
        "#);
    }
}
