//! Documentation text transformations.
//!
//! Converts `$ `‐prefixed `console` code blocks into calls to Zola's `terminal`
//! component, and fences off the template syntax Worktrunk *documents* so Zola
//! doesn't try to evaluate it. Used by both the `--help-page` generator (CLI
//! source → web docs) and the doc sync test (hand-written docs → web docs).
//!
//! Zola 0.23 (Tera2) removed shortcodes in favour of components and started
//! rendering every `.md` file through the template engine, which is what makes
//! the second transformation necessary: a documented minijinja example such as
//! `{{ branch | hash_port }}` is otherwise read as a Zola expression and fails
//! the build. [`wrap_template_syntax`] wraps those in `{% raw %}`, and
//! [`strip_template_syntax_wrappers`] recovers the source form — the doc sync
//! test strips on read and wraps on write so a page compares against its
//! source form, not its published one. Recovery covers the wrapper forms this
//! module emits, which is not the same as every text an author could write:
//! see [`strip_template_syntax_wrappers`] for the one shape it can't tell from
//! documented text.

/// Empty span; the displayed "EXPERIMENTAL" text comes from the CSS `::after`
/// rule so the anchor-link slug generated by Zola ignores it.
///
/// Lives here (rather than in `src/help.rs`) so the producer (the `--help-page`
/// post-processor that emits this in place of `[experimental]`) and the
/// consumer (the skill-file generator that strips it back to `[experimental]`)
/// stay in lockstep — changing the badge in one place would otherwise let
/// stale HTML leak silently into skill files.
pub const BADGE_EXPERIMENTAL_HTML: &str = "<span class=\"badge-experimental\"></span>";

/// HTML-comment marker that includes a subcommand's `--help-page` body inline
/// in its parent's `after_long_help`. Expanded into an H2 section by
/// `expand_subdoc_placeholders`. Trailing space included so `find()` and
/// `strip_prefix()` agree on the boundary.
pub const SUBDOC_MARKER_PREFIX: &str = "<!-- subdoc: ";

/// HTML-comment marker that pulls a demo GIF from `worktrunk-assets` into the
/// docs site (rendered as a `<picture>` figure). Stripped from skill output.
pub const DEMO_MARKER_PREFIX: &str = "<!-- demo: ";

/// Open-marker prefix for an auto-generated region in a docs file.
/// Followed by `<id> — edit <source> to update -->`. Both `--help-page` (the
/// producer in `src/help.rs`) and the doc-sync test (the consumer in
/// `tests/integration_tests/readme_sync.rs`) reference this so the literal
/// can't drift between sides.
pub const MARKER_OPEN_PREFIX: &str = "<!-- ⚠️ AUTO-GENERATED from ";

/// Close marker for an auto-generated region. Paired with `MARKER_OPEN_PREFIX`
/// via non-greedy regex matching; the sync test
/// `test_no_nested_auto_generated_markers` enforces the no-nesting precondition
/// that makes that pairing safe.
pub const MARKER_CLOSE: &str = "<!-- END AUTO-GENERATED -->";

/// Convert `$ `‐prefixed console blocks into `terminal` component calls.
///
/// All shell commands in `console` blocks use `$ ` prefix. This function detects
/// them and emits the appropriate call form:
///
/// - Commands without output: `{{ <terminal cmd="..." /> }}` (Syntect highlighting)
/// - Commands with output: `{% <terminal cmd="..."> %}output{% </terminal> %}`
/// - Multiple commands/comments: `|||`‐delimited in `cmd` parameter
///
/// `{{ }}` in commands (e.g., Jinja2 template expressions) are replaced with
/// placeholders so Tera doesn't interpret them. The `terminal` component
/// replaces them back before Syntect highlighting. Double quotes and backslashes
/// get the same treatment: the first would close the `cmd="..."` argument, and
/// the second is Tera2's string-escape character, so a shell continuation `\`
/// left as-is is either an "unexpected escape character" build error or —
/// worse, for a sequence Tera2 does recognise — a silent rewrite.
///
/// Blocks without `$ ` are left unchanged for the `console` → `bash` replacement.
pub fn convert_dollar_console_to_terminal(text: &str) -> String {
    let mut result = String::with_capacity(text.len());
    let mut lines = text.lines().peekable();

    while let Some(line) = lines.next() {
        if line.trim_start() == "```console" {
            // Collect the block, then decide whether to convert
            let mut block_lines = Vec::new();
            for content_line in lines.by_ref() {
                let stripped = content_line.trim_start();
                if stripped.starts_with("```")
                    && (stripped.len() == 3 || !stripped.as_bytes()[3].is_ascii_alphabetic())
                {
                    break;
                }
                block_lines.push(content_line);
            }

            // Only convert if the block contains $ commands
            let commands: Vec<_> = block_lines
                .iter()
                .filter_map(|l| l.strip_prefix("$ "))
                .collect();

            if commands.is_empty() {
                // No $ lines — emit unchanged as console block
                result.push_str(line);
                result.push('\n');
                for bl in &block_lines {
                    result.push_str(bl);
                    result.push('\n');
                }
                result.push_str("```\n");
                continue;
            }

            // Classify each line into the cmd= stream (rendered with prompt
            // prefix and Syntect highlighting, joined by `|||`) or the output
            // body. `$ <cmd>` lines feed cmd= verbatim (with `"` and `{{`/`}}`
            // escaped past Tera); `#` lines feed cmd= so the template styles
            // them as bash-comment section headers (used by the `wt list` jq
            // recipes block). Blank lines belong to whichever side has content
            // — to cmd= when the block is command-only (visual spacing between
            // recipe groups), to body otherwise.
            let has_output = block_lines
                .iter()
                .any(|l| !l.is_empty() && !l.starts_with("$ ") && !l.starts_with('#'));
            let mut cmd_value: Vec<String> = Vec::new();
            let mut body_lines: Vec<&&str> = Vec::new();
            for line in &block_lines {
                if let Some(cmd) = line.strip_prefix("$ ") {
                    cmd_value.push(
                        cmd.replace('\\', "__WT_BSLASH__")
                            .replace('"', "__WT_QUOT__")
                            .replace("{{", "__WT_OPEN__")
                            .replace("}}", "__WT_CLOSE__"),
                    );
                } else if line.starts_with('#') || (line.is_empty() && !has_output) {
                    cmd_value.push((*line).to_string());
                } else {
                    body_lines.push(line);
                }
            }

            let cmd_str = cmd_value.join("|||");
            if body_lines.is_empty() {
                result.push_str(&format!("{{{{ <terminal cmd=\"{cmd_str}\" /> }}}}\n"));
            } else {
                result.push_str(&format!("{{% <terminal cmd=\"{cmd_str}\"> %}}\n"));
                for bl in &body_lines {
                    result.push_str(bl);
                    result.push('\n');
                }
                result.push_str("{% </terminal> %}\n");
            }
            continue;
        }
        result.push_str(line);
        result.push('\n');
    }

    // .lines() strips the trailing newline; match original
    if !text.ends_with('\n') {
        result.pop();
    }
    result
}

/// The one sequence a `{% raw %}` region cannot contain: its own terminator.
/// Emitted in its place, closing the region, printing the literal through a
/// string expression, and reopening. Both halves of the wrap/strip pair key on
/// this exact text.
const ENDRAW_ESCAPE: &str = r#"{% endraw %}{{ "{% endraw %}" }}{% raw %}"#;

const RAW_OPEN: &str = "{% raw %}";
const RAW_CLOSE: &str = "{% endraw %}";

/// True for a line that calls a Zola component (`{{ <terminal … /> }}`,
/// `{% <terminal …> %}`, `{% </terminal> %}`) and so must stay evaluable.
fn is_component_call(line: &str) -> bool {
    let t = line.trim_start();
    t.starts_with("{{ <") || t.starts_with("{% <")
}

fn has_template_syntax(text: &str) -> bool {
    text.contains("{{") || text.contains("{%")
}

/// Opening fence marker (``` or ~~~, three or more) with its indentation, if
/// this line opens or closes a fenced code block.
fn fence_marker(line: &str) -> Option<(&str, &str)> {
    let indent_len = line.len() - line.trim_start().len();
    let (indent, rest) = line.split_at(indent_len);
    for ch in ['`', '~'] {
        let run = rest.chars().take_while(|c| *c == ch).count();
        if run >= 3 {
            return Some((indent, &rest[..run]));
        }
    }
    None
}

/// Fence off the template syntax the docs *document* so Zola renders it
/// literally instead of evaluating it.
///
/// Zola 0.23 templates every `.md` file, so a documented `{{ branch }}` is a
/// build error rather than text. Wrapping is line-granular — a fenced block
/// that contains template syntax is wrapped whole, any other line carrying it
/// is wrapped in place — which keeps the markers off the ~95% of lines that
/// have no template syntax at all, and keeps each wrap's output byte-identical
/// to its input.
///
/// Component calls are left evaluable, since they are the reason content
/// templating stays on. Everything else is literal.
///
/// Idempotent: strips any existing wrappers first, so the doc sync test can run
/// this over a page it already wrote.
pub fn wrap_template_syntax(text: &str) -> String {
    let stripped = strip_template_syntax_wrappers(text);
    let ends_with_newline = stripped.ends_with('\n');
    let lines: Vec<&str> = stripped.lines().collect();

    // Front matter is TOML read before templating; leave it alone.
    let start = if lines.first() == Some(&"+++") {
        lines
            .iter()
            .skip(1)
            .position(|l| *l == "+++")
            .map_or(0, |i| i + 2)
    } else {
        0
    };

    let mut out: Vec<String> = lines[..start].iter().map(|l| (*l).to_string()).collect();
    let mut i = start;
    while i < lines.len() {
        let line = lines[i];
        if let Some((indent, marker)) = fence_marker(line) {
            let mut block = vec![line];
            i += 1;
            while i < lines.len() {
                let closes = lines[i].trim() == marker;
                block.push(lines[i]);
                i += 1;
                if closes {
                    break;
                }
            }
            let joined = block.join("\n");
            if has_template_syntax(&joined) {
                out.push(format!("{indent}{RAW_OPEN}"));
                out.extend(
                    joined
                        .replace(RAW_CLOSE, ENDRAW_ESCAPE)
                        .lines()
                        .map(String::from),
                );
                out.push(format!("{indent}{RAW_CLOSE}"));
            } else {
                out.extend(block.into_iter().map(String::from));
            }
            continue;
        }
        if has_template_syntax(line) && !is_component_call(line) {
            out.push(format!(
                "{RAW_OPEN}{}{RAW_CLOSE}",
                line.replace(RAW_CLOSE, ENDRAW_ESCAPE)
            ));
        } else {
            out.push(line.to_string());
        }
        i += 1;
    }

    let mut result = out.join("\n");
    if ends_with_newline {
        result.push('\n');
    }
    result
}

/// Inverse of [`wrap_template_syntax`] — recover the source form of a page.
///
/// Only the wrapper *forms* this module emits are recovered: a marker alone on
/// its line, a line opened and closed by one, and the `ENDRAW_ESCAPE` sequence.
/// A marker alone on its line is indistinguishable from documented text and is
/// dropped either way, so document `{% raw %}` / `{% endraw %}` mid-line (as
/// `extending.md` and `faq.md` do) and never alone on a line.
pub fn strip_template_syntax_wrappers(text: &str) -> String {
    let text = text.replace(ENDRAW_ESCAPE, RAW_CLOSE);
    let ends_with_newline = text.ends_with('\n');
    let mut out: Vec<&str> = Vec::new();
    for line in text.lines() {
        let trimmed = line.trim();
        if trimmed == RAW_OPEN || trimmed == RAW_CLOSE {
            continue;
        }
        let line = line
            .strip_prefix(RAW_OPEN)
            .and_then(|l| l.strip_suffix(RAW_CLOSE))
            .unwrap_or(line);
        out.push(line);
    }
    let mut result = out.join("\n");
    if ends_with_newline {
        result.push('\n');
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;
    use insta::assert_snapshot;

    #[test]
    fn test_wrap_template_syntax_round_trips() {
        let source = r#"+++
title = "config"
+++

Set `{{ branch }}` in the template:

```toml
worktree-path = "{{ repo_path }}/{{ branch }}"
```

{{ <terminal cmd="wt switch feat" /> }}

Plain prose stays untouched.
"#;
        let wrapped = wrap_template_syntax(source);
        assert_snapshot!(wrapped, @r#"
        +++
        title = "config"
        +++

        {% raw %}Set `{{ branch }}` in the template:{% endraw %}

        {% raw %}
        ```toml
        worktree-path = "{{ repo_path }}/{{ branch }}"
        ```
        {% endraw %}

        {{ <terminal cmd="wt switch feat" /> }}

        Plain prose stays untouched.
        "#);
        assert_eq!(strip_template_syntax_wrappers(&wrapped), source);
        // Wrapping an already-wrapped page is a no-op.
        assert_eq!(wrap_template_syntax(&wrapped), wrapped);
    }

    #[test]
    fn test_wrap_template_syntax_escapes_documented_endraw() {
        // extending.md documents minijinja's own `raw`, so the literal
        // terminator has to survive a region that would otherwise end on it.
        let source = "Wrap it as `{% raw %}{{ branch }}{% endraw %}` to defer.\n";
        let wrapped = wrap_template_syntax(source);
        assert_snapshot!(wrapped, @r#"{% raw %}Wrap it as `{% raw %}{{ branch }}{% endraw %}{{ "{% endraw %}" }}{% raw %}` to defer.{% endraw %}"#);
        assert_eq!(strip_template_syntax_wrappers(&wrapped), source);
    }

    #[test]
    fn test_convert_dollar_console_to_terminal() {
        // Command+output with {{ }} → cmd parameter with placeholders
        assert_snapshot!(convert_dollar_console_to_terminal(
            "```console\n$ wt step eval '{{ branch | hash_port }}'\n16066\n```"
        ), @r#"
        {% <terminal cmd="wt step eval '__WT_OPEN__ branch | hash_port __WT_CLOSE__'"> %}
        16066
        {% </terminal> %}
        "#);

        // Command only (no $) → unchanged
        assert_snapshot!(convert_dollar_console_to_terminal(
            "```console\nwt step commit --stage=tracked\n```"
        ), @r"
        ```console
        wt step commit --stage=tracked
        ```
        ");

        // Multi-line output, no {{ }} → cmd parameter
        assert_snapshot!(convert_dollar_console_to_terminal(
            "```console\n$ wt step eval -v 'test'\n○ Available template variables\n  branch = feature/auth\ntest\n```"
        ), @r#"
        {% <terminal cmd="wt step eval -v 'test'"> %}
        ○ Available template variables
          branch = feature/auth
        test
        {% </terminal> %}
        "#);

        // Single command with output, no {{ }} → cmd parameter
        assert_snapshot!(convert_dollar_console_to_terminal(
            "```console\n$ echo 'PORT=8080' > .env\noutput\n```"
        ), @r#"
        {% <terminal cmd="echo 'PORT=8080' > .env"> %}
        output
        {% </terminal> %}
        "#);

        // Command only (single, no output) → self-closing call
        assert_snapshot!(convert_dollar_console_to_terminal(
            "```console\n$ wt remove\n```"
        ), @r#"{{ <terminal cmd="wt remove" /> }}
        "#);

        // Multiple commands → |||‐delimited cmd with Syntect highlighting
        assert_snapshot!(convert_dollar_console_to_terminal(
            "```console\n$ wt step push\n$ wt step push develop\n```"
        ), @r#"{{ <terminal cmd="wt step push|||wt step push develop" /> }}
        "#);

        // Comment before $ commands → included in cmd, Syntect highlights as comment
        assert_snapshot!(convert_dollar_console_to_terminal(
            "```console\n# Recent commands\n$ tail -5 log.jsonl | jq .\n\n# Failed\n$ jq 'select(.exit != 0)' log.jsonl\n```"
        ), @r##"{{ <terminal cmd="# Recent commands|||tail -5 log.jsonl | jq .||||||# Failed|||jq 'select(.exit != 0)' log.jsonl" /> }}
        "##);

        // Blank line in mixed-mode block (cmd + output) stays in body, doesn't
        // leak into cmd= as a stray `$ ` prompt.
        assert_snapshot!(convert_dollar_console_to_terminal(
            "```console\n$ wt list\n  Branch  Status\n@ main\n\n○ Showing 1 worktree\n```"
        ), @r#"
        {% <terminal cmd="wt list"> %}
          Branch  Status
        @ main

        ○ Showing 1 worktree
        {% </terminal> %}
        "#);
    }
}
